name: 🐛 Bug Report
description: Help us improve this repository by filing a detailed bug report.
title: '[bug]: '
labels: [ 'issue: bug', 'status: to be confirmed' ]
body:
  - type: markdown
    attributes:
      value: |
        Bug Description |
        A clear and concise description of the problem or unexpected behavior (attach screenshots/gifs if appropriate). |
        Clicking on the "Save" button doesn’t save the form data. |
  - type: markdown
    attributes:
      value: |
         Steps to Reproduce |
         Provide a step-by-step description of how to reproduce the issue. Include code snippets or links to repositories when applicable.|
         label: |
           Example: |
             1. Go to '...' |
             2. Click on '...' |
             3. Scroll down to '...' |
             4. See error |
  - type: markdown
    attributes:
      value: |
        Expected Behavior |
        Describe what you expected to happen instead of the bug. Be as specific as possible. |
  - type: input
    attributes:
      label: Version
      description: The SDK version used
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: Select the operating system you are experiencing the issue on.
      multiple: false
      options:
        - MacOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Runtime Environment
      description: Select the environment where this issue occurs.
      multiple: false
      options:
        - Browser
        - Node.js
        - Other (bun, deno, ...)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmation Checklist
      options:
        - label: I have searched for duplicates and couldn’t find a similar issue.
        - label: I have provided all necessary details to reproduce the issue.
