name: 🐛 Bug Report
description: Help us improve this repository by filing a detailed bug report.
title: '[bug]: '
labels: [ 'issue: bug', 'status: to be confirmed' ]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of the problem or unexpected behavior (attach screenshots/gifs if appropriate).
      placeholder: Clicking on the "Save" button doesn’t save the form data.
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step description of how to reproduce the issue. Include code snippets or links to repositories when applicable.
      placeholder: |
        Example:
          1. Create an Article collection type in your Strapi app
          2. Export the API schema
          3. Make the following query: `...`
          4. See the error in the console
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead of the bug. Be as specific as possible.
      render: markdown
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: The SDK version used
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: Select the operating system you are experiencing the issue on.
      multiple: false
      options:
        - MacOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Runtime Environment
      description: Select the environment where this issue occurs.
      multiple: false
      options:
        - Browser
        - Node.js
        - Other (bun, deno, ...)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs
      description: If applicable, the logs you got from using the SDK
      render: shell

  - type: checkboxes
    attributes:
      label: Confirmation Checklist
      options:
        - label: I have searched for duplicates and couldn’t find a similar issue.
        - label: I have provided all necessary details to reproduce the issue.
